### ISSUE TITLE
Dirty Phrasebook(part II)

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#103]
推荐理由：dirty-phrasebook第二部分
链接：https://blog.stylingandroid.com/dirty-phrasebook-part-2/
@BillionWang

**Comment by xu6148152** [comment]
update title

**Comment by hehonghui** [comment]
注意看作者关于他文章的版权声明，加上这个版权声明就OK。https://blog.stylingandroid.com/license-information/ 。用这个网站可以生成模板，http://creativecommons.org/choose/ 。
