### ISSUE TITLE
Introduction to Model-View-Presenter on Android

### ISSUE THREAD

**Issue by clawwave** [bboyfeiyu/android-tech-frontier#106]
推荐理由：mvp
链接：http://konmik.github.io/introduction-to-model-view-presenter-on-android.html

**Comment by hehonghui** [comment]
@chaossss 你的同学的github账户后续评论进来吧

**Comment by ponyfe** [comment]
@liangpengfei我认领咯

**Comment by hehonghui** [comment]
@liangpengfei  还写过v2ex的客户端啊，不错啊小伙~  欢迎加入

**Comment by hehonghui** [comment]
这个issue为什么关闭了 ？

2015-04-28 11:51 GMT+08:00 Chaos notifications@github.com:
