### ISSUE TITLE
How to install different app variants on one Android device

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#107]
推荐理由：在同一个Android设备上同时安装不用app的variants
链接：https://blog.grandcentrix.net/how-to-install-different-app-variants-on-one-android-device/

我来@xu6148152，感觉挺有意思的。

**Comment by bboyfeiyu** [comment]
@xu6148152 你最近比较忙哈，给你减轻一下负担，:) 。我把你这篇交给@SwinZ 了，谢啦。

**Comment by xu6148152** [comment]
@bboyfeiyu  这个issue帮我分出去吧。谢谢。

**Comment by hehonghui** [comment]
@MrLoong 可以先看看这篇

**Comment by hehonghui** [comment]
@MrLoong 这篇你翻译吗 ？

**Comment by MrLoong** [comment]
[@bboyfeiyu](https://github.com/bboyfeiyu)这篇我没有翻译，我翻译的另一个
