### ISSUE TITLE
Tasting Dagger 2 on Android

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#109]
推荐理由：Dagger2尝试
链接：http://fernandocejas.com/2015/04/11/tasting-dagger-2-on-android/

我自己明天翻译。

**Comment by xu6148152** [comment]
@xu6148152

**Comment by xu6148152** [comment]
已经翻译了一部分，但这段时间比较忙，因此属于我的都要延后了。

**Comment by xianjiajun** [comment]
已认领。

**Comment by hehonghui** [comment]
@xianjiajun 这篇咋样了 ？

**Comment by xianjiajun** [comment]
@bboyfeiyu 之前翻译了一半了。用的作业部落在线编辑，在家里打开的时候发现同步丢失了很多。又要重新写。。

**Comment by hehonghui** [comment]
@xianjiajun 还是用git管理比较靠谱呐~

**Comment by xianjiajun** [comment]
@bboyfeiyu 作业部落可以预览结果和云同步，感觉还是可以，不知道为什么这次丢失了。这篇有点长，我这周之类提交翻译。

**Comment by hehonghui** [comment]
@xianjiajun 好的，辛苦啦 :)
