### ISSUE TITLE
ListView或者RecycleView滚动时隐藏Toolbar(Part 2)

### ISSUE THREAD

**Issue by chaossss** [bboyfeiyu/android-tech-frontier#11]
- issue 标题: 推荐: ListView或者RecycleView滚动时隐藏Toolbar
- 文章来源：[How-to-hideshow-Toolbar-when-list-is-scrolling(part2)/](http://mzgreen.github.io/2015/02/28/How-to-hideshow-Toolbar-when-list-is-scrolling%28part2%29/)
- 推荐原因：ListView或者RecycleView滚动时隐藏Toolbar系列作者写的第二篇介绍博文
- 标签: others
- milestone: 2015/02

**Comment by hehonghui** [comment]
@chaossss 你要认领了哪个来着 ？

**Comment by chaossss** [comment]
support-multiple-themes-android-app，这个已经翻好了

**Comment by hehonghui** [comment]
@chaossss  这篇就交给你啦~

**Comment by chaossss** [comment]
好，明天我先粗翻一下……过几天有空把这两篇一起润色

**Comment by hehonghui** [comment]
不着急的，看你的时间。
