### ISSUE TITLE
Against Android Unit Tests

### ISSUE THREAD

**Issue by clawwave** [bboyfeiyu/android-tech-frontier#110]
推荐理由：Against Android Unit Tests
链接：http://philosophicalhacker.com/2015/04/10/against-android-unit-tests/

**Comment by sundroid** [comment]
@sundroid 认领

**Comment by clawwave** [comment]
@sundroid 认领

**Comment by hehonghui** [comment]
@sundroid 这个咋样了 ？

**Comment by clawwave** [comment]
@bboyfeiyu  稍等啊

**Comment by chaossss** [comment]
@sundroid 这篇我好像在翻译 part1的时候顺手翻了，当时我不知道有这个issue……

https://github.com/bboyfeiyu/android-tech-frontier/blob/master/issue-8/Android%20%E8%BF%9B%E8%A1%8C%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%E9%9A%BE%E5%9C%A8%E5%93%AA-%E5%BA%8F.md
