### ISSUE TITLE
Retrofit Android Tutorial

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#111]
推荐理由：Retrofit教程
链接：http://themakeinfo.com/2015/04/retrofit-android-tutorial/

**Comment by ghost** [comment]
@yaoqinwei

**Comment by likebamboo** [comment]
"Volley is a small library compared to Retrofit ,but it is undocumented. "  翻译成了”与Retrofit相比，Volley是一个小型库，但它是非法的。“ undocumented是 ”非法“ 的意思？ 我读书少，不要骗我。

**Comment by KevinYaoooooo** [comment]
查了下词典，不知道如何翻译好，用这词确实不怎么好，你的建议是？@likebamboo   ,BTW，这是我公司的Github号

**Comment by PoarryScript** [comment]
翻译成    非官方的 怎么样？

**Comment by KevinYaoooooo** [comment]
ok cool @PoarryScript

**Comment by Gracker** [comment]
是不是说：没有“开源许可证” 的意思？

**Comment by likebamboo** [comment]
undocumented 翻译 ”文档匮乏“是否更好？  ”与Retrofit相比，Volley是一个小型库，但没有文档介绍“

**Comment by ghost** [comment]
同意楼上的

**Comment by KevinYaoooooo** [comment]
@likebamboo sounds good

**Comment by KevinYaoooooo** [comment]
@Lollypo @likebamboo @PoarryScript changed: "Volley是一个小型库，而且缺乏官方文档"

**Comment by PoarryScript** [comment]
perfect

**Comment by andyiac** [comment]
api 19 以后volley 貌似已经加入到SDK中去了
