### ISSUE TITLE
Introduction to CocoaPods Tutorial

### ISSUE THREAD

**Issue by ghost** [bboyfeiyu/android-tech-frontier#121]
推荐理由： 超级详细的CocoaPods指南
链接：http://www.raywenderlich.com/64546/introduction-to-cocoapods-2
@Lollypo我自己来

**Comment by hehonghui** [comment]
@Lollypo 先提来这里，:) https://github.com/bboyfeiyu/iOS-tech-frontier/

**Comment by xu6148152** [comment]
nice

**Comment by ghost** [comment]
转到https://github.com/bboyfeiyu/iOS-tech-frontier项目中了
