### ISSUE TITLE
RxBus-Implementing an Event Bus With RxJava

### ISSUE THREAD

**Issue by DoAndKeep** [bboyfeiyu/android-tech-frontier#125]
- 推荐理由：这是一篇关于RxJava应用的优秀文章
- 原文链接：http://nerds.weddingpartyapp.com/tech/2014/12/24/implementing-an-event-bus-with-rxjava-rxbus/
- 标签：RxJava EventBus
- 来源：Android Blog
- milestone：2015/04

**Comment by hehonghui** [comment]
:)

**Comment by DoAndKeep** [comment]
@FILWAndroid 认领

**Comment by hehonghui** [comment]
@FILWAndroid 啥情况 ？
