### ISSUE TITLE
Android Support Library 22.1

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#138]
推荐理由 : Android Support Library 22.1
原文链接 : http://android-developers.blogspot.com/2015/04/android-support-library-221.html

**Comment by tiiime** [comment]
@tiiime 认领

**Comment by hehonghui** [comment]
@tiiime 你先待定哈，有个新人想加入，我想用这篇稿子审核，不然没稿子了。看看他今晚能不能搞定先。 :)

**Comment by tiiime** [comment]
ok👌
