### ISSUE TITLE
这是一篇关于RxJava响应式编程的优秀文章

### ISSUE THREAD

**Issue by jtsky** [bboyfeiyu/android-tech-frontier#139]
原文链接：http://reactivex.io/RxJava/javadoc/rx/Observable.html

**Comment by hehonghui** [comment]
@jtsky 是否相似 ？ https://github.com/bboyfeiyu/android-tech-frontier/tree/master/androidweekly/%E9%82%A3%E4%BA%9B%E5%B9%B4%E6%88%91%E4%BB%AC%E9%94%99%E8%BF%87%E7%9A%84%E5%93%8D%E5%BA%94%E5%BC%8F%E7%BC%96%E7%A8%8B
