### ISSUE TITLE
What’s new in Android Testing Droidcon Italy 2015

### ISSUE THREAD

**Issue by zhengxiaopeng** [bboyfeiyu/android-tech-frontier#150]
推荐理由：The next generation of Android Testing Tools
原文链接：[What’s new in Android Testing Droidcon Italy 2015 ](https://docs.google.com/presentation/d/1EtFKPluGiuxZcr4W_cAziEY_--wbY_1otw44XEBv7JA/edit#slide=id.g98a986571_0_269) （PPT）

**Comment by zhengxiaopeng** [comment]
@zhengxiaopeng

**Comment by zhengxiaopeng** [comment]
需要否？

**Comment by hehonghui** [comment]
@zhengxiaopeng PPT我们暂且不翻译了吧。找些文章来翻译好了。 :)
