### ISSUE TITLE
NotRxJava

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#158]
- 原文链接 : http://yarikx.github.io/NotRxJava/

**Comment by zhengxiaopeng** [comment]
@zhengxiaopeng 认领

**Comment by MrLoong** [comment]
[@MirLoong](https://github.com/MrLoong)

**Comment by MrLoong** [comment]
[@MirLoong认领](https://github.com/MrLoong)

**Comment by hehonghui** [comment]
@MrLoong 已经有人翻译了，只是状态还没修改过来。另外@zhengxiaopeng 这是本期重要文章，多费心哈。本周需要发布这篇文章，谢谢。
