### ISSUE TITLE
Missing Android Material Components

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#160]
推荐理由：Missing Android Material Components
原文链接：http://www.dmytrodanylyk.com/pages/blog/missing-material-components.html

**Comment by wly2014** [comment]
我来翻译吧

**Comment by MrLoong** [comment]
[@MrLoong认领](https://github.com/MrLoong)

**Comment by hehonghui** [comment]
这篇是哪位负责的呢 ?
