### ISSUE TITLE
这是一篇Android Studio单元测试的指导文章

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [bboyfeiyu/android-tech-frontier#162]
推荐原因：Android Studio单元测试的指导文章
原文链接: http://rexstjohn.com/unit-testing-with-android-studio/
标签: android studio ,Unit Testing
milestone: 2015/04

**Comment by ZhaoKaiQiang** [comment]
@bboyfeiyu @chaossss ， @ZhaoKaiQiang 认领

**Comment by ayyb1988** [comment]
@ZhaoKaiQiang 你认领了吗？

**Comment by ayyb1988** [comment]
@bboyfeiyu    认领

**Comment by ZhaoKaiQiang** [comment]
@ayyb1988 已经翻译完了 你可以校对
