### ISSUE TITLE
Building a RecyclerView LayoutManager

### ISSUE THREAD

**Issue by lovetuzitong** [bboyfeiyu/android-tech-frontier#167]
- **推荐理由**：不错的RecyclerView进阶教程
- **Url**：[http://wiresareobsolete.com/2014/09/building-a-recyclerview-layoutmanager-part-1/](http://wiresareobsolete.com/2014/09/building-a-recyclerview-layoutmanager-part-1/)

**Comment by lovetuzitong** [comment]
系列文章：[Part1](http://wiresareobsolete.com/2014/09/building-a-recyclerview-layoutmanager-part-1/), [Part2](http://wiresareobsolete.com/2014/09/recyclerview-layoutmanager-2/), [Part3](http://wiresareobsolete.com/2015/02/recyclerview-layoutmanager-3/)

**Comment by hehonghui** [comment]
@lovetuzitong  挺好的资料，多谢推荐。欢迎推荐更多的文章哈 :)

**Comment by tiiime** [comment]
认领 @bboyfeiyu

**Comment by hehonghui** [comment]
@tiiime 你把另外几个部分也提到issue中吧，让别人可以领这个任务。谢啦

**Comment by tiiime** [comment]
嗯

**Comment by MrLoong** [comment]
[@MrLoong认领](https://github.com/MrLoong)

**Comment by chaossss** [comment]
@MrLoong  https://github.com/bboyfeiyu/android-tech-frontier/issues/167 已经有人在翻译了哦

**Comment by tiiime** [comment]
翻译完成 等待校对 @chaossss
