### ISSUE TITLE
Building a RecyclerView LayoutManager Part-2

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#168]
推荐人: @lovetuzitong  
推荐理由：不错的RecyclerView进阶教程
Url：http://wiresareobsolete.com/2014/09/recyclerview-layoutmanager-2/

**Comment by clawwave** [comment]
@sundroid 认领

**Comment by hehonghui** [comment]
@sundroid 咋样了？

**Comment by hehonghui** [comment]
@sundroid 咋样呐？这篇文章估计需要这周发出了。
