### ISSUE TITLE
Building a RecyclerView LayoutManager Part-3

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#169]
推荐人: @lovetuzitong  
推荐理由：不错的RecyclerView进阶教程
Url：http://wiresareobsolete.com/2015/02/recyclerview-layoutmanager-3/

**Comment by hehonghui** [comment]
@lovetuzitong 欢迎提交issue :) ,另外 @tiiime  在提交issue时你可以添加label

**Comment by tiiime** [comment]
@bboyfeiyu 我好像还没有添加 label 的权限啊

**Comment by hehonghui** [comment]
@tiiime 已经添加了，我看错啦~   :)

**Comment by hehonghui** [comment]
@tmc9031 翻译这篇文章，辛苦啦。:)

**Comment by tmc9031** [comment]
@bboyfeiyu UI的文章不太熟，取消认领

**Comment by hehonghui** [comment]
@tiiime 你要接吗 ？

**Comment by tiiime** [comment]
认领 @bboyfeiyu

**Comment by hehonghui** [comment]
@tiiime 咋样了 ？

**Comment by tiiime** [comment]
翻译中 最近就能提交
