### ISSUE TITLE
How to add a Native Facebook Like Button to your Android app using Facebook SDK for Android v4

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#174]
推荐理由：How to add a Native Facebook Like Button to your Android app using Facebook SDK for Android v4  
原文链接：http://inthecheesefactory.com/blog/how-to-add-facebook-like-button-in-android-app/en

**Comment by wangyuyan666** [comment]
@bboyfeiyu 重新认领这篇

**Comment by hehonghui** [comment]
@objectlife OK，已经修改状态
