### ISSUE TITLE
Adventures in Android: User Notifications

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#175]
推荐理由：Adventures in Android: User Notifications
原文链接：https://medium.com/@Bicx/adventures-in-android-user-notifications-e6568871d9be

**Comment by xu6148152** [comment]
@bboyfeiyu  这段时间实在是忙，欠的债暂时补不上。后面会补上，现在只能看看ISSUE.添加一些ISSUE了。实在抱歉。

**Comment by hehonghui** [comment]
@xu6148152 没问题，多谢支持哈。已经在iOS和Android都给了你管理员权限，你添加issue的时候可以设置相关的label了。另外我们帮你把一些任务分出去吧，你领了不少任务哈，搁置了挺长时间啦。:)

**Comment by MrLoong** [comment]
[@MrLoong请求认领](https://github.com/MrLoong)

**Comment by hehonghui** [comment]
@MrLoong OK,给你了。或者你可以看看更早的有没有还没翻译的，时间多点的可以多看看哈

**Comment by hehonghui** [comment]
@MrLoong 这篇文章还没有翻译吧？ 如果没有的话就不翻译这篇文章了吧。
