### ISSUE TITLE
如何让Android App可测试

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#177]
- 推荐理由 : App的可测试性
- 原文链接 : http://philosophicalhacker.com/2015/05/01/how-to-make-our-android-apps-unit-testable-pt-1/

**Comment by objectlife** [comment]
@bboyfeiyu 认领

**Comment by chaossss** [comment]
@objectlife  这篇已经有人认领了哦，只是忘了改状态了，不好意思哈

**Comment by wangyuyan666** [comment]
@chaossss  这个就是你认领的吧。。。。

**Comment by chaossss** [comment]
@objectlife 恩，这一个系列都是我负责的，校对也是有指定的人的呐

**Comment by wangyuyan666** [comment]
@chaossss 我昨天翻译的时候也注意到了其它的几篇文章了。

**Comment by chaossss** [comment]
@chaossss 恩，序言，part1，part2，都已经校对完成pr了，这边能看到序和p1，p2下一期会放出来

**Comment by wangyuyan666** [comment]
@chaossss 我先把群加上吧。
