### ISSUE TITLE
关于如何在本地搭建一个Android应用crashing跟踪系统－ACRA的问题

### ISSUE THREAD

**Issue by ruijun** [bboyfeiyu/android-tech-frontier#179]
我在本地搭建一个Android应用crashing跟踪系统－ACRA的时候，安装的CouchDB版本是1.0.1。怎样才能安装到1.2.0版本呢？

**Comment by hehonghui** [comment]
@ruijun 这里不是问技术问题的地方，你google一下或者到开发群问一问吧。:)
