### ISSUE TITLE
Introduction to Model-View-Presenter on Android

### ISSUE THREAD

**Issue by ayyb1988** [bboyfeiyu/android-tech-frontier#183]
- 推荐理由 :  Introduction to Model-View-Presenter on Android
- 原文链接 : http://konmik.github.io/introduction-to-model-view-presenter-on-android.html

**Comment by hehonghui** [comment]
@ayyb1988 请按照规范来添加issue ，另外MVP的文章已经挺多了，你看看这篇是否需要翻译 ？

**Comment by MiJack** [comment]
认领

**Comment by MiJack** [comment]
@MiJack认领

**Comment by MiJack** [comment]
认领

**Comment by MiJack** [comment]
翻译完成，已添加PR

**Comment by MiJack** [comment]
校对完成
