### ISSUE TITLE
Mastering the	Android Touch System

### ISSUE THREAD

**Issue by THEONE10211024** [bboyfeiyu/android-tech-frontier#187]
推荐人: @THEONE10211024

推荐理由：目前看见的讲Android Touch事件最好的文章
Url：http://wugengxin.cn/download/pdf/android/PRE_andevcon_mastering-the-android-touch-system.pdf

**Comment by hehonghui** [comment]
@THEONE10211024 这篇你可以翻译一下咯 :) ，看到不少文章引用了这篇文章的内容。

**Comment by xianjiajun** [comment]
@bboyfeiyu 这篇文章有人翻译没？

**Comment by KayWu** [comment]
这个应该是[Masterring the Android Touch System](https://www.youtube.com/watch?v=EZAoJU-nUyI)所用的PPT。
中文的PPT没看到过，[中文字幕的视频](http://v.youku.com/v_show/id_XODM4NzA3ODMy.html?f=23088492)倒是有。

**Comment by hehonghui** [comment]
@KayWu 我也是看到过几次这个PPT,多谢提供资料哈。:)

**Comment by hehonghui** [comment]
@xianjiajun 这篇似乎没有人翻译~ 你有兴趣可以看看
