### ISSUE TITLE
leak-canary库文档

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#196]
- 推荐理由 : leak-canary, 内存泄露检测
- 原文链接 : [leakcanary](https://github.com/square/leakcanary)。

**Comment by ayyb1988** [comment]
@bboyfeiyu    ayyb1988 认领

**Comment by xu6148152** [comment]
重复了，liaoliuqiu已经翻译完了。
http://www.liaohuqiu.net/cn/posts/leak-canary/

**Comment by bboyfeiyu** [comment]
ok ，那就放弃这篇。 @ayyb1988

**Comment by hehonghui** [comment]
@xu6148152 我们把官方文档翻译一下好了。那篇文章已经去掉了，有两个人都翻译了

**Comment by ayyb1988** [comment]
@bboyfeiyu  官方文档   liaoliuqiu也已经翻译过了
http://www.liaohuqiu.net/cn/posts/leak-canary-read-me/

把这个关闭吧。

**Comment by hehonghui** [comment]
OK 。
