### ISSUE TITLE
Frame Animations in Android

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#217]
推荐理由：Frame Animations in Android
原文链接：https://www.bignerdranch.com/blog/frame-animations-in-android/

**Comment by hehonghui** [comment]
@objectlife 这篇你翻译的么 ？

**Comment by wangyuyan666** [comment]
@bboyfeiyu 真不好意思~这段时间事儿有点多，我把这个给忘了。把这个放开吧。不好意思哈。

**Comment by jianghejie** [comment]
@jianghejie  这个我已经翻译完了 就认领了吧。。。
