### ISSUE TITLE
The mysterious case of the Bundle and the Map

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#24]
- 推荐理由 : 深入了解Bundle和Map
- 原文链接 : [The mysterious case of the Bundle and the Map](https://medium.com/the-wtf-files/the-mysterious-case-of-the-bundle-and-the-map-7b15279a794e)
- 译者 : @yinna317

**Comment by hehonghui** [comment]
@yinna317 啥情况了？ 不会忘了吧

**Comment by yinna317** [comment]
没有，翻译了一遍，还要修改下。不好意思啊，这几天在忙，QQ也没怎么登，周六前提交可以吗？

**Comment by hehonghui** [comment]
@yinna317 没有问题的，我只是怕忘了~
