### ISSUE TITLE
 How to add ink ripple touch feedback to an image

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#253]
推荐理由：How to add ink ripple touch feedback to an image
原文链接：https://plus.google.com/+NickButcher/posts/azEU6s4APbu

**Comment by ghost** [comment]
potatofan

**Comment by hehonghui** [comment]
@potatofan 翻译得咋样了 ？

**Comment by chaossss** [comment]
@potatofan 翻译得咋样了 ？
