### ISSUE TITLE
 Manual Layout Transitions – Part 4

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#255]
推荐理由：Manual Layout Transitions – Part 4
原文链接：https://blog.stylingandroid.com/manual-layout-transitions-part-4/

**Comment by jianghejie** [comment]
@jianghejie 认领

**Comment by chaossss** [comment]
@jianghejie 翻译得咋样了 ？

**Comment by hehonghui** [comment]
@chaossss 子乐，这篇已经发到 http://www.jcodecraeer.com/ 上了，我只是没有从他那边拷贝过来，你有时间可以转过来我们网站上。

**Comment by jianghejie** [comment]
我本来看到simple已经翻译了前三篇，以为simple会接着翻译，本来是告诉simple接过来的。所以就没提交，可能simple比较忙吧，结果它没有继续翻译了。我网站上是翻译完了，可以随意转载。

**Comment by chaossss** [comment]
@jianghejie  恩，我已经转载了
