### ISSUE TITLE
 Introduction to Android reference counting mechanism

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#256]
推荐理由：Introduction to Android reference counting mechanism
原文链接：http://pierrchen.blogspot.com/2015/06/introduction-to-android-reference.html

**Comment by ichibown** [comment]
@tiiime  认领

**Comment by hehonghui** [comment]
@BownX 什么进展了 ？

**Comment by ichibown** [comment]
啊忘了更新这里了，上周已经merge了~ #278 
麻烦close一下这个吧

**Comment by hehonghui** [comment]
@BownX OK，是C++那篇，刚才没看原文。 :)
