### ISSUE TITLE
THINGS YOU MAY NOT KNOW: ONRESUMEFRAGMENTS

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#271]
推荐理由：THINGS YOU MAY NOT KNOW: ONRESUMEFRAGMENTS
原文链接: http://www.randomlytyping.com/blog/2015/6/5/things-you-may-not-know-about-onresumefragments

**Comment by jianghejie** [comment]
@jianghejie 翻译认领
