### ISSUE TITLE
PSA: fix MultiDex build crashes

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#277]
推荐理由：PSA: fix MultiDex build crashes
原文链接: https://medium.com/sebs-top-tips/psa-fix-multidex-build-crashes-ae2b81bcf711

**Comment by zijianwang90** [comment]
认领喽

**Comment by zijianwang90** [comment]
但是我又仔细看了下文章，想确认下这个有必要翻译吗？说道最后就是在build.gradle里配置一行话而已。。

**Comment by hehonghui** [comment]
@zijianwang90 翻译一下吧，就相当于我们网站上做个索引。你可以再领一篇嘛。:)

**Comment by zijianwang90** [comment]
好的，快搞定了
