### ISSUE TITLE
检测和解决Android的性能问题

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#284]
[detect-and-resolve-performance-problems-on-android](http://code.tutsplus.com/tutorials/detect-and-resolve-performance-problems-on-android--cms-24058)

**Comment by MiJack** [comment]
认领

**Comment by hehonghui** [comment]
@MrJack 这篇文章怎么样了？

**Comment by MiJack** [comment]
最近比较忙，正在翻译中

**Comment by hehonghui** [comment]
@MiJack 我已经翻译了。

**Comment by MiJack** [comment]
谢谢，麻烦你啦
