### ISSUE TITLE
如何发布代码库到jcenter和maven center

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#288]
[how-to-upload-library-to-jcenter-maven-central-as-dependency](http://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en)

**Comment by jianghejie** [comment]
@jianghejie  已经翻译完了

**Comment by hehonghui** [comment]
@jianghejie 可以发个pr过来。 :)
