### ISSUE TITLE
Navigation Drawer styling according to Material Design

### ISSUE THREAD

**Issue by wly2014** [bboyfeiyu/android-tech-frontier#29]
- 推荐理由 : Material Design侧滑菜单
- 原文链接 : https://medium.com/@sotti/navigation-drawer-styling-according-material-design-5306190da08f

**Comment by hehonghui** [comment]
@wly2014 认领该文章

**Comment by hehonghui** [comment]
@wly2014 进度咋样了 ？

**Comment by hehonghui** [comment]
http://androidweekly.net/issues/issue-145
