### ISSUE TITLE
如何提升你的代码质量

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#294]
[http://vincentbrison.com/2014/07/19/how-to-improve-quality-and-syntax-of-your-android-code/](http://vincentbrison.com/2014/07/19/how-to-improve-quality-and-syntax-of-your-android-code/)

**Comment by tiiime** [comment]
@tiiime 认领

**Comment by hehonghui** [comment]
@tiiime 这篇咋样了 ？

**Comment by tiiime** [comment]
暂时不能翻译了  交给别人吧 :(

2015-06-29 18:21 GMT+08:00 Mr.Simple notifications@github.com:

**Comment by hehonghui** [comment]
@tiiime  ok

**Comment by andoter0501** [comment]
maybe，i can do it,I have spent ten minutes on this article.

**Comment by hehonghui** [comment]
@dengshiwei 交给你啦

**Comment by andoter0501** [comment]
好的，不出意外，今天就翻译完成了，晚上在校验下，第一次做这个，多多见谅

**Comment by hehonghui** [comment]
@dengshiwei 没事，能参与就是好事。 :)

**Comment by andoter0501** [comment]
已经请求push
