### ISSUE TITLE
Instagram的Material Design Part-1

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#296]
[http://frogermcs.github.io/Instagram-with-Material-Design-concept-is-getting-real/](http://frogermcs.github.io/Instagram-with-Material-Design-concept-is-getting-real/)
[译文链接](http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/0204/2415.html)

**Comment by wangyuyan666** [comment]
@bboyfeiyu 这篇文章网上已经有了。http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/0204/2415.html  你看一下是否需要继续翻译。

**Comment by hehonghui** [comment]
@objectlife 这篇不用翻译，我只是做个标记。泡在网上的日子很早就有了，有时间我会转载过来的。
