### ISSUE TITLE
使用RxJava从几个数据源中加载数据

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#303]
[http://blog.danlew.net/2015/06/22/loading-data-from-multiple-sources-with-rxjava/](http://blog.danlew.net/2015/06/22/loading-data-from-multiple-sources-with-rxjava/)

**Comment by yinshijian-kkb** [comment]
@bboyfeiyu  认领该文章

**Comment by yinshijian-kkb** [comment]
pr 已经merge
