### ISSUE TITLE
在你的Crash报告中使用git SHA

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#304]
[http://www.donnfelker.com/why-you-should-use-a-git-sha-in-your-crash-reporting/](http://www.donnfelker.com/why-you-should-use-a-git-sha-in-your-crash-reporting/)

**Comment by yinshijian-kkb** [comment]
@bboyfeiyu 认领该文章

**Comment by yinshijian-kkb** [comment]
pr 已经merge
