### ISSUE TITLE
do it

### ISSUE THREAD

**Issue by andoter0501** [bboyfeiyu/android-tech-frontier#306]
我对这篇文字有兴趣，也是第一次参与，希望翻译这篇文章

**Comment by tiiime** [comment]
是 《如何提升你的代码质量 》 这篇文章吗 ？如果是我已将任务标记好了哈。翻译完提交pr就可以啦，还有请按照[README](https://github.com/bboyfeiyu/android-tech-frontier/blob/master/README.md) 参与步骤提交issus 。 还有什么问题可以邮件联系 : )

**Comment by andoter0501** [comment]
是这篇文章，第一次做这个，顺便学习下git怎么玩的，我已进行翻译了。
