### ISSUE TITLE
Android Activity测试

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#308]
[http://developer.android.com/intl/zh-cn/tools/testing/activity_testing.html](http://developer.android.com/intl/zh-cn/tools/testing/activity_testing.html)

**Comment by andoter0501** [comment]
打不开啊

**Comment by hehonghui** [comment]
得翻墙

2015-07-02 8:50 GMT+08:00 MyGit_dsw notifications@github.com:

**Comment by lujiahao0708** [comment]
我可以试试吗？

**Comment by hehonghui** [comment]
可以
2015年7月12日 下午9:08于 "路家豪" notifications@github.com写道：

**Comment by desmond1121** [comment]
@desmond1121 认领文章
