### ISSUE TITLE
Android Service测试

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#309]
[http://developer.android.com/intl/zh-cn/tools/testing/service_testing.html](http://developer.android.com/intl/zh-cn/tools/testing/service_testing.html)

**Comment by yinshijian-kkb** [comment]
@bboyfeiyu 认领该文章

**Comment by hehonghui** [comment]
@yinshijian-kkb 咋样了 ？

**Comment by yinshijian-kkb** [comment]
大致翻译完啦

**Comment by hehonghui** [comment]
@yinshijian-kkb OK，谢啦
