### ISSUE TITLE
应用超链接跳转

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#314]
[http://nerds.airbnb.com/deeplinkdispatch/](http://nerds.airbnb.com/deeplinkdispatch/)

**Comment by youxincao** [comment]
@bboyfeiyu 认领该文章

**Comment by hehonghui** [comment]
@youxincao 这篇忘了翻译吗 ？

**Comment by stuhua** [comment]
有人翻译的没？
