### ISSUE TITLE
测试使用RxJava的代码

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#316]
[https://medium.com/ribot-labs/unit-testing-rxjava-6e9540d4a329](https://medium.com/ribot-labs/unit-testing-rxjava-6e9540d4a329)

**Comment by andoter0501** [comment]
为什么新建的issue就没有显示啊！是这篇

**Comment by hehonghui** [comment]
@dengshiwei 指定给你了哈

**Comment by andoter0501** [comment]
ok

**Comment by andoter0501** [comment]
翻译完成，请求校验，那些状态【翻译中】之类的怎么添加的

**Comment by hehonghui** [comment]
@dengshiwei 管理员才可以修改状态的，我给你添加一下权限。

**Comment by andoter0501** [comment]
哦，我也不懂，没事。

**Comment by andoter0501** [comment]
已经完成校验
