### ISSUE TITLE
Binder 框架解析

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#317]
[http://events.linuxfoundation.org/images/stories/slides/abs2013_gargentas.pdf](http://events.linuxfoundation.org/images/stories/slides/abs2013_gargentas.pdf)

**Comment by andoter0501** [comment]
这篇不错，讲解Binder的用法，有点多啊！六十页，估计要花费很长时间

**Comment by Freedom000** [comment]
Binder 就60多页？

**Comment by andoter0501** [comment]
是译为外国朋友写的，具体没怎么看，浏览了下，估计应该和底层的关系介绍吧！60页，写下他对Binder的理解，已经很不错了。

**Comment by yinshijian-kkb** [comment]
@bboyfeiyu  认领该篇文章

**Comment by hehonghui** [comment]
@yinshijian-kkb 咋样了 ？

**Comment by seasonmac** [comment]
这个ppt真的有必要翻译吗？已经很浅显了

**Comment by hehonghui** [comment]
@seasonpplp 很多都挺浅显的，只是翻译出来会让更多的人看罢了。

**Comment by yinshijian-kkb** [comment]
翻译完了，现在在整格式 @bboyfeiyu
