### ISSUE TITLE
Android灵活的、可测试的应用架构

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#329]
[原文链接](http://www.philosophicalhacker.com/2015/07/07/mvpr-a-flexible-testable-architecture-for-android-pt-1/)

**Comment by chaossss** [comment]
@chaossss

**Comment by hehonghui** [comment]
@chaossss 咋样了 ？

**Comment by andoter0501** [comment]
如果有机会，我可以周末参与这个翻译，因为近来对架构的文章颇感兴趣，SM哥推荐几个吧！

**Comment by hehonghui** [comment]
@dengshiwei 你可以看看martin fowler的文章，可以翻译那些文章过来。http://martinfowler.com/design.html 。:)

**Comment by chaossss** [comment]
@bboyfeiyu 忘了pr了……晚点pr上去
