### ISSUE TITLE
Gradle Tasks Ordering

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#331]
[原文链接](http://trickyandroid.com/gradle-tip-3-tasks-ordering/)

**Comment by FTExplore** [comment]
FTExplore 认领,这个系列上一篇就是我翻译的，所以这一篇还是我吧，语言风格会统一一些

**Comment by hehonghui** [comment]
@FTExplore 这篇文章发布了没有来着 ?
