### ISSUE TITLE
Android架构演化之路

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#332]
[http://fernandocejas.com/2015/07/18/architecting-android-the-evolution/](http://fernandocejas.com/2015/07/18/architecting-android-the-evolution/)

**Comment by wangyuyan666** [comment]
认领

**Comment by objectlife** [comment]
翻译了一点。。这段时间比较忙，没时间继续翻译了，就先放开吧。

**Comment by wangyuyan666** [comment]
翻译了一点。。这段时间比较忙，没时间继续翻译了，就先放开吧。

**Comment by hehonghui** [comment]
@objectlife markdown文件有吗 ？

**Comment by bboyfeiyu** [comment]
@objectlife markdown文件有吗 ？

**Comment by bboyfeiyu** [comment]
@objectlife markdown文件有吗 ？

**Comment by dustookk** [comment]
认领 ：）

**Comment by hehonghui** [comment]
@dustookk 高兄好快

**Comment by andoter0501** [comment]
@dustookk 翻译的怎么样了，亲

**Comment by dustookk** [comment]
快完事儿了  之前太忙了 抱歉...

**Comment by andoter0501** [comment]
没事，理解万岁
