### ISSUE TITLE
Android中的AOP编程

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#339]
[aspect-oriented-programming-in-android](http://fernandocejas.com/2014/08/03/aspect-oriented-programming-in-android/)

**Comment by byronwind** [comment]
@byronwind 认领

**Comment by hehonghui** [comment]
@byronwind 今天能搞定么 ？

**Comment by byronwind** [comment]
抱歉，@bboyfeiyu 今天才搞定

**Comment by hehonghui** [comment]
@byronwind 没事，多谢贡献哈
