### ISSUE TITLE
Glide是如何优化图片加载的

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#343]
[glide-how-yelps-android-app-loads-images.html](http://engineeringblog.yelp.com/2015/07/glide-how-yelps-android-app-loads-images.html)

**Comment by tiiime** [comment]
@tiiime 认领

**Comment by hehonghui** [comment]
@tiiime 今天能搞定么？

**Comment by tiiime** [comment]
可以  晚上给你

**Comment by hehonghui** [comment]
@tiiime OK，谢啦
