### ISSUE TITLE
使用TDD的方式开发一个Hacknews客户端

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#344]
[making-a-tdd-based-hackernews-client-for-android](http://www.philosophicalhacker.com/2015/07/17/making-a-tdd-based-hackernews-client-for-android/)

**Comment by Anthonyeef** [comment]
认领

**Comment by hehonghui** [comment]
@Anthonyeef 多谢贡献

**Comment by Anthonyeef** [comment]
已翻译完成。另外，我觉得标题应该是 HackerNews 客户端，而不是 HackNews 。
