### ISSUE TITLE
TextView的Text Layout （Facebook博客）

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#346]
[multiple-text-layout](https://sriramramani.wordpress.com/2014/08/14/multiple-text-layout/)

**Comment by andoter0501** [comment]
mark,这个周末我来翻译吧！SM哥，你哪里找的这么多文章啊

**Comment by andoter0501** [comment]
这个可能要晚点，因为最近在翻译mockito

**Comment by hehonghui** [comment]
@dengshiwei OK，没问题哈，这个不着急。

**Comment by andoter0501** [comment]
翻译完成，请求校验
