### ISSUE TITLE
在instamaterial中使用Design Support Library控件

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#348]
[instamaterial-meets-design-support-library](http://frogermcs.github.io/instamaterial-meets-design-support-library/)

**Comment by Kyson** [comment]
http://www.open-open.com/lib/view/open1438065235675.html
有人翻译过了。

**Comment by hehonghui** [comment]
@Kyson 这篇会用另外一个网站上的翻译。所以这篇不翻译了。
