### ISSUE TITLE
CoordinatorLayout 的快速跳转

### ISSUE THREAD

**Issue by tiiime** [bboyfeiyu/android-tech-frontier#377]
[Quick return with CoordinatorLayout](https://medium.com/@bherbst/quick-return-with-recyclerview-e70c8da9b4c1)

**Comment by tiiime** [comment]
@tiiime 认领

**Comment by hehonghui** [comment]
tiiime你需要书么 ？还有名额

2015-08-17 13:00 GMT+08:00 kang notifications@github.com:
