### ISSUE TITLE
Kotlin for Android (II): Create a new project

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#38]
- 推荐理由 : Kotlin，让Android开发更简洁
- 原文链接 : http://antonioleiva.com/kotlin-android-create-project/
- 来源 : Android Weekly

欢迎有兴趣的同学认领该翻译项目。

**Comment by ghost** [comment]
这个我试着翻翻，感觉挺有趣的样子~
