### ISSUE TITLE
android ui development made easy

### ISSUE THREAD

**Issue by ghost** [bboyfeiyu/android-tech-frontier#39]
推荐理由: 一种与注解来将开发者从findViewByid中解放出来完全不一样的方式
原文链接: http://zserge.com/blog/android-mvx.html

**Comment by chaossss** [comment]
@chaossss 认领

**Comment by hehonghui** [comment]
@chaossss @Lollypo @sundroid @allenlsy 以后把图放到图床上，别放在仓库里面，不然很大。我的图片是存在CSDN上，如果原图不翻墙可以访问那就直接使用原图链接。
