### ISSUE TITLE
Approaching Android with MVVM

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#416]
[https://medium.com/ribot-labs/approaching-android-with-mvvm-8ceec02d5442](https://medium.com/ribot-labs/approaching-android-with-mvvm-8ceec02d5442)

**Comment by zimoguo** [comment]
@zimoguo

**Comment by hehonghui** [comment]
@zimoguo 子墨，忘了这篇文章啦  ？
