### ISSUE TITLE
Intro to Functional Reactive Programming

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#432]
[Intro to Functional Reactive Programming](https://realm.io/news/droidcon-gomez-functional-reactive-programming/?utm_source=Android+Weekly&utm_campaign=553bcbfc02-Android_Weekly_174&utm_medium=email&utm_term=0_4eb677ad19-553bcbfc02-337955857)

**Comment by kevinhong** [comment]
@kevinhong 认领

**Comment by hehonghui** [comment]
@kevinhong 这篇文章提交了吗 ？
