### ISSUE TITLE
Why use Observable.create() and not just inherit from Observable?

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#433]
[Why use Observable.create() and not just inherit from Observable?](http://www.grokkingandroid.com/why-use-observable-create-and-not-just-inherit-from-observable/?utm_source=Android+Weekly&utm_campaign=553bcbfc02-Android_Weekly_174&utm_medium=email&utm_term=0_4eb677ad19-553bcbfc02-337955857)

**Comment by andoter0501** [comment]
mark，认领
