### ISSUE TITLE
Espresso: Save and restore state

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#434]
[link](http://blog.sqisland.com/2015/10/espresso-save-and-restore-state.html?utm_source=Android+Weekly&utm_campaign=553bcbfc02-Android_Weekly_174&utm_medium=email&utm_term=0_4eb677ad19-553bcbfc02-337955857)

**Comment by DroidWorkerLYF** [comment]
@DroidWorkerLYF 认领
