### ISSUE TITLE
Vectors For All

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#442]
[link](https://blog.stylingandroid.com/vectors-for-all-almost/?utm_source=Android+Weekly&utm_campaign=0903213dbd-Android_Weekly_175&utm_medium=email&utm_term=0_4eb677ad19-0903213dbd-337955857)

**Comment by DroidWorkerLYF** [comment]
@DroidWorkerLYF认领该翻译任务
