### ISSUE TITLE
Designing Android Apps For Vision Impaired Users

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#443]
[link](http://novoda.com/blog/designing-android-apps-with-vision-impaired-users-in-mind/?utm_source=Android+Weekly&utm_campaign=0903213dbd-Android_Weekly_175&utm_medium=email&utm_term=0_4eb677ad19-0903213dbd-337955857)

**Comment by pinehallnick** [comment]
nickzhangdianxinba

**Comment by pinehallnick** [comment]
hi desmond1121, which issues this page include?

**Comment by desmond1121** [comment]
@nickzhangdianxinba sorry，之前忘记处理了，你可以放到androidweekly文件夹中

**Comment by hehonghui** [comment]
@nickzhangdianxinba 这篇怎么样了 ？

**Comment by chaossss** [comment]
没翻好我晚上弄了……

**Comment by zhangxiaofan918** [comment]
sorry一直比较忙，忘了看这个提醒了

**Comment by pinehallnick** [comment]
sorry一直比较忙，忘了看这个提醒了
