### ISSUE TITLE
Develop a secured Android application

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#444]
[link](http://blog.octo.com/en/develop-secured-android-application/?utm_source=Android+Weekly&utm_campaign=0903213dbd-Android_Weekly_175&utm_medium=email&utm_term=0_4eb677ad19-0903213dbd-337955857)

**Comment by kevinhong** [comment]
@kevinhong 认领

**Comment by kevinhong** [comment]
翻译好了，已pr
