### ISSUE TITLE
Beware EditText on API 21

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#445]
[link](http://blog.danlew.net/2015/10/12/beware-edittext-on-api-21/?utm_source=Android+Weekly&utm_campaign=0903213dbd-Android_Weekly_175&utm_medium=email&utm_term=0_4eb677ad19-0903213dbd-337955857)

**Comment by isiyin** [comment]
@xiaolangpapa 认领
