### ISSUE TITLE
Debugging RxJava on Android

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#462]
[link](http://fernandocejas.com/2015/11/05/debugging-rxjava-on-android/?utm_source=Android+Weekly&utm_campaign=038d344835-Android_Weekly_178&utm_medium=email&utm_term=0_4eb677ad19-038d344835-337955857)

**Comment by shenyansycn** [comment]
@shenyansycn 我来吧。
