### ISSUE TITLE
Having Trouble Focusing? A Primer on Focus in Android

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#465]
[link](https://www.novoda.com/blog/do-you-even-focus-bro/?utm_source=Android+Weekly&utm_campaign=faec756f5a-Android_Weekly_179&utm_medium=email&utm_term=0_4eb677ad19-faec756f5a-337955857)

**Comment by qknow-w** [comment]
这个可以认领不？

**Comment by andoter0501** [comment]
@503945930 可以，因为上面没人mark认领，你是第一个可以认领

**Comment by qknow-w** [comment]
嗯  认领。
