### ISSUE TITLE
Triggering a native Share intent on Android from the web

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#466]
[link](https://paul.kinlan.me/sharing-natively-on-android-from-the-web/?utm_source=Android+Weekly&utm_campaign=faec756f5a-Android_Weekly_179&utm_medium=email&utm_term=0_4eb677ad19-faec756f5a-337955857)

**Comment by qknow-w** [comment]
刚学习android不久，希望可以一起学习。可以认领么。

**Comment by desmond1121** [comment]
@503945930 没问题，不过不好意思，我忘记关了这个issue， 这篇已经被翻译了，可以挑另外的领

**Comment by qknow-w** [comment]
嗯 好的
