### ISSUE TITLE
Recyclerview Animations Part 1,2

### ISSUE THREAD

**Issue by zhehuaz** [bboyfeiyu/android-tech-frontier#467]
推荐理由: 这是一篇关于recyclerview动画的优秀文章
原文链接: http://www.birbit.com/recyclerview-animations-part-2-behind-the-scenes/
                http://www.birbit.com/recyclerview-animations-part-1-how-animations-work/

**Comment by shenyansycn** [comment]
@shenyansycn 我认领两部。
