### ISSUE TITLE
Overscroll AppBarLayout Behavior

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#472]
[link](https://medium.com/@nullthemall/overscroll-appbarlayout-behavior-e58f1ee2807#.dcn63knem)

**Comment by liuling07** [comment]
@liuling07

**Comment by liuling07** [comment]
@liuling07

**Comment by desmond1121** [comment]
@liuling07 抱歉之前没看见，现在添加标签了。 以后下面@自己后直接可以翻译，译好pr即可。

**Comment by liuling07** [comment]
@desmond1121 前段时间有点忙，今天才翻译完，麻烦校对一下。https://github.com/bboyfeiyu/android-tech-frontier/pull/512/files
