### ISSUE TITLE
Scissors: an image cropping library for Android

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#474]
[link](https://eng.lyft.com/scissors-an-image-cropping-library-for-android-a56369154a19#.jsghjkniv)

**Comment by Damonzh** [comment]
@desmond1121  新手不知道可以认领这篇文章不

**Comment by desmond1121** [comment]
@Damonzh 可以

**Comment by Damonzh** [comment]
@desmond1121  初稿已经翻译完了 并且已经提交pr ^_^
