### ISSUE TITLE
An Introduction to Face Detection on Android

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#476]
[link](http://code.tutsplus.com/tutorials/an-introduction-to-face-detection-on-android--cms-25212?utm_source=Android+Weekly&utm_campaign=15ee59bb7a-Android_Weekly_181&utm_medium=email&utm_term=0_4eb677ad19-15ee59bb7a-337955857)

**Comment by zhehuaz** [comment]
@LangleyChang
