### ISSUE TITLE
Android Performance Case Study Follow-up

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#48]
- 推荐理由 : Romain Guy 性能优化
- 推荐链接 : http://www.curious-creature.com/2015/03/25/android-performance-case-study-follow-up/?utm_source=Android+Weekly&utm_campaign=0692ef161b-Android_Weekly_146&utm_medium=email&utm_term=0_4eb677ad19-0692ef161b-337914749

**Comment by chaossss** [comment]
@chaossss 认领

**Comment by hehonghui** [comment]
android weekly 146期，http://androidweekly.net/issues/issue-146。

**Comment by leerduo** [comment]
@leerduo 认领

**Comment by hehonghui** [comment]
@chaossss 放弃这篇文章的翻译，@leerduo 来翻译吧，辛苦啦

**Comment by hehonghui** [comment]
@leerduo  怎么样了 ？
