### ISSUE TITLE
Gradle tip #1,2,3,4

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#489]
- [1-tasks](http://trickyandroid.com/gradle-tip-1-tasks/) 
- [2-syntax](http://trickyandroid.com/gradle-tip-2-understanding-syntax/)
- [3-task ordering](http://trickyandroid.com/gradle-tip-3-tasks-ordering/)
- [4-Gradle tip #4: Log unit test execution events into console](http://trickyandroid.com/gradle-tip-4-log-unit-test-execution-events-into-console/)

**Comment by Damonzh** [comment]
@desmond1121 我先试着翻一下第一部分吧

**Comment by desmond1121** [comment]
@Damonzh ok

**Comment by Damonzh** [comment]
@desmond1121 看完了，我全领了吧 ^_^。 很好的系列文，之前看过gradle的介绍，都是看的稀里糊涂的，这篇看完印象深刻。

**Comment by desmond1121** [comment]
@Damonzh 好的，辛苦了
