### ISSUE TITLE
stetho-for-android-debug-builds-only

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#49]
- 推荐理由 : Facebook的调试工具stetho
- 原文链接 : http://littlerobots.nl/blog/stetho-for-android-debug-builds-only/?utm_source=Android+Weekly&utm_campaign=0692ef161b-Android_Weekly_146&utm_medium=email&utm_term=0_4eb677ad19-0692ef161b-337914749
- 译者 :

**Comment by ghost** [comment]
@billionwang

**Comment by hehonghui** [comment]
@billionwang 修哥的活~

**Comment by hehonghui** [comment]
android weekly 146期，http://androidweekly.net/issues/issue-146。
