### ISSUE TITLE
introducing-fresco-a-new-image-library-for-android/

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#50]
- 推荐理由 : Facebook新的图片加载库Fresco
- 原文链接 : https://code.facebook.com/posts/366199913563917/introducing-fresco-a-new-image-library-for-android/
- 译者 :

**Comment by ZhaoKaiQiang** [comment]
我如果要认领的话，应该怎么办呢

**Comment by ZhaoKaiQiang** [comment]
@ZhaoKaiQiang  认领该任务

**Comment by hehonghui** [comment]
android weekly 146期，http://androidweekly.net/issues/issue-146

**Comment by ZhaoKaiQiang** [comment]
website is  wrong

**Comment by chaossss** [comment]
@ZhaoKaiQiang  已修正

**Comment by soyoungboy** [comment]
这个可以看下这个http://fresco-cn.org/docs/download-fresco.html

**Comment by ZhaoKaiQiang** [comment]
Thanks

**Comment by hehonghui** [comment]
@soyoungboy 给的资料不错

**Comment by soyoungboy** [comment]
@bboyfeiyu 我也是今天看到的，顺便分享出来，好东西得让大家都知道

**Comment by hehonghui** [comment]
@soyoungboy en，我也刚从代码家的订阅列表里看到。多谢分享

**Comment by hehonghui** [comment]
@ZhaoKaiQiang 这篇文章比较重要，可要注意质量噢。  @chaossss 首席翻译 + 校对，靠你监督了。

**Comment by ZhaoKaiQiang** [comment]
@bboyfeiyu @chaossss 已翻译完，等待校对
