### ISSUE TITLE
Dagger 2

### ISSUE THREAD

**Issue by androidMVP** [bboyfeiyu/android-tech-frontier#503]
推荐理由: 这是一篇关于Dagger 2的优秀文章
原文链接: https://blog.gouline.net/2015/05/04/dagger-2-even-sharper-less-square/
来源:blog.gouline.net
milestone: 2015/012

**Comment by desmond1121** [comment]
@androidMVP 可以，你翻译吧，翻译好了pr即可:)

**Comment by androidMVP** [comment]
但是没有原文作者同意授权....

**Comment by Zkffkah** [comment]
@Lowwor 我来先翻了吧。

**Comment by maoruibin** [comment]
可以一起翻译吗？正好前段时间看过这篇文章，写的很不错 @lowwor

**Comment by Zkffkah** [comment]
@maoruibin 提了pr了，一起看一下呗。

**Comment by maoruibin** [comment]
OK ~
