### ISSUE TITLE
why would i want to fitssystemwindows?[android weekly]

### ISSUE THREAD

**Issue by LionelCursor** [bboyfeiyu/android-tech-frontier#505]
我翻译了这个，放上来可否？
[原文](https://medium.com/google-developers/why-would-i-want-to-fitssystemwindows-4e26d9ce1eec?linkId=19685562#.q1ojx0ebi)

**Comment by desmond1121** [comment]
@LionelCursor 欢迎

**Comment by LionelCursor** [comment]
那篇文章被合进去了，但是仍然是校对中状态
