### ISSUE TITLE
Gradle tips & tricks to survive the zombie apocalypse

### ISSUE THREAD

**Issue by yuweiguocn** [bboyfeiyu/android-tech-frontier#508]
推荐理由: 这是一篇关于Gradle 的优秀文章
原文链接: https://medium.com/@cesarmcferreira/gradle-tips-tricks-to-survive-the-zombie-apocalypse-3dd996604341#.gqvpzyvj4
标签: androidweekly#185
milestone: 2015/12

**Comment by desmond1121** [comment]
@yuweiguocn 可以，翻译后pr即可

**Comment by hehonghui** [comment]
@yuweiguocn 卫国兄你翻译么  ？

**Comment by yuweiguocn** [comment]
嗯，正在翻

**Comment by yuweiguocn** [comment]
@yuweiguocn 认领
