### ISSUE TITLE
Twitter's like animation in Android - alternative

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#509]
[link](http://frogermcs.github.io/twitters-like-animation-in-android-alternative/）

**Comment by hanks-zyh** [comment]
是要找这个吗？http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/1224/3799.html

**Comment by desmond1121** [comment]
@hanks-zyh 原来已经翻译过了，谢谢指出，我close掉
