### ISSUE TITLE
The analytics checklist: what to measure and look for

### ISSUE THREAD

**Issue by ghost** [bboyfeiyu/android-tech-frontier#51]
推荐理由 : 分析App使用情况的数据~
原文链接 : http://cogitas.net/blog/2015/03/27/the-analytics-checklist-what-to-measure-and-look-for/

**Comment by ghost** [comment]
@zimoguo

**Comment by ghost** [comment]
子墨妹纸上吧

**Comment by hehonghui** [comment]
android weekly 146期，http://androidweekly.net/issues/issue-146。

**Comment by hehonghui** [comment]
无人翻译，且价值不大，暂时关闭。
