### ISSUE TITLE
Efficiency and fun from using ADB Shell, Part 1

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#523]
[link](https://ar-g.github.io/ADB-Shell-Part-1/?utm_source=Android+Weekly&utm_campaign=9ed0cecaff-Android_Weekly_186&utm_medium=email&utm_term=0_4eb677ad19-9ed0cecaff-337955857)

**Comment by DroidWorkerLYF** [comment]
@DroidWorkerLYF 认领
