### ISSUE TITLE
 Using concurrency to improve speed and performance on Android

### ISSUE THREAD

**Issue by yuweiguocn** [bboyfeiyu/android-tech-frontier#529]
推荐理由: 这是一篇关于提高Android性能的优秀文章
原文链接: https://medium.com/@ali.muzaffar/using-concurrency-and-speed-and-performance-on-android-d00ab4c5c8e3#.t1ynou5e3
标签: androidweekly
milestone: 2016/01

**Comment by desmond1121** [comment]
@yuweiguocn 可以

**Comment by yuweiguocn** [comment]
@yuweiguocn 认领

**Comment by yuweiguocn** [comment]
@desmond1121 另一篇就交给别的同学翻译吧，我怕时间拖太长
