### ISSUE TITLE
Creating custom Text Selection actions with ACTION_PROCESS_TEXT

### ISSUE THREAD

**Issue by yuweiguocn** [bboyfeiyu/android-tech-frontier#531]
推荐理由: 这是一篇关于Android文本选择的优秀文章
原文链接: https://medium.com/google-developers/custom-text-selection-actions-with-action-process-text-191f792d2999?linkId=20000023#.eqi4s7tvh
标签: androidweekly#186
milestone: 2016/01

**Comment by 471448446** [comment]
访问不了

**Comment by desmond1121** [comment]
@yuweiguocn 可以，翻译后pr吧

**Comment by hehonghui** [comment]
@471448446 确定翻译吗 ？

**Comment by yuweiguocn** [comment]
@yuweiguocn 认领
