### ISSUE TITLE
Fragment Transactions & Activity State Loss

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#532]
[link](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html)

**Comment by andoter0501** [comment]
mark,交给我吧

**Comment by andoter0501** [comment]
真不好意思，这个可能翻译不了了，最近都在加班了，麻烦移出标签，转给其他人吧

**Comment by isiyin** [comment]
似曾相识的文章，@xiaolangpapa 认领

**Comment by chaossss** [comment]
没翻好我晚上弄了……

**Comment by isiyin** [comment]
@chaossss 翻译中，预计今晚提PR

**Comment by chaossss** [comment]
@xiaolangpapa 昨晚弄完了
