### ISSUE TITLE
How to Leak a Context: Handlers & Inner Classes

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#533]
[link](http://www.androiddesignpatterns.com/2013/01/inner-class-handler-memory-leak.html)

**Comment by Damonzh** [comment]
@desmond1121 领了

**Comment by hehonghui** [comment]
@desmond1121 这种那么老的文章怎么还发呀  ？

**Comment by andoter0501** [comment]
@bboyfeiyu 主要是讲解一些问题吧！
