### ISSUE TITLE
Android Studio Tips and Tricks

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#543]
[link](http://michaelevans.org/blog/2016/01/06/android-studio-tips-and-tricks/)

**Comment by shenyansycn** [comment]
@shenyansycn 我认领

**Comment by Glowin** [comment]
这篇文章我们掘金翻译计划已经翻译完成了，如果有需要的话，获得我们译者@laobie 同意后 androidweekly 可以发表在周刊里面呢。

https://github.com/xitu/gold-miner/pull/95
