### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#560]
- [part1](https://blog.stylingandroid.com/permissions-part-1/) 
- [part2](https://blog.stylingandroid.com/permissions-part-2/) 
- [part3](https://blog.stylingandroid.com/permissions-part-3/) 
- [part4](https://blog.stylingandroid.com/permissions-part-4/)

**Comment by shenyansycn** [comment]
@shenyansycn 我来弄系列文章
