### ISSUE TITLE
Crunching on RxAndroid

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#562]
- [Intro](https://medium.com/crunching-rxandroid/crunching-rxandroid-intro-c27eb6f009ea#.6kkec416a) 未认领
- [part1](https://medium.com/crunching-rxandroid/crunching-rxandroid-part-1-4ac7b7123238#.6cdxodhds)未认领
- [part2](https://medium.com/crunching-rxandroid/crunching-rxandroid-part-2-fb2a86f4fb8d#.ylr6j4l2e)未认领
- [part3](https://medium.com/crunching-rxandroid/crunching-rxandroid-part-3-91fc9a619b7b#.arg838b2p)未认领
- [part4](https://medium.com/crunching-rxandroid/crunching-rxandroid-part-4-b2c3771ad52d#.bbmtayhxx)未认领
- [part5](https://medium.com/crunching-rxandroid/crunching-rxandroid-part-5-1dd5fba89058#.cgt8nixmr)未认领
- [part6](https://medium.com/crunching-rxandroid/crunching-rxandroid-part-6-6149764b59e#.4s80bjfni)未认领

**Comment by Damonzh** [comment]
@desmond1121  领了
