### ISSUE TITLE
Implementing video playback in a scrolled list (ListView & RecyclerView)

### ISSUE THREAD

**Issue by chaossss** [bboyfeiyu/android-tech-frontier#564]
[Implementing video playback in a scrolled list (ListView & RecyclerView)](https://medium.com/@v.danylo/implementing-video-playback-in-a-scrolled-list-listview-recyclerview-d04bc2148429#.wu7va9kgz)

**Comment by chaossss** [comment]
@chaossss

**Comment by vijaycis** [comment]
How to play live url in Listview & RecyclerView.Please suggest me.
