### ISSUE TITLE
The Reactive Revolution: RxAndroid and how it finally clicked for me

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#568]
[part1](https://medium.com/@carl.whalley/the-reactive-revolution-rxandroid-and-how-it-finally-clicked-for-me-part-1-of-2-a35122a6091e#.4f6yjerlt)
[part2](https://medium.com/@carl.whalley/the-reactive-revolution-rxandroid-and-how-it-finally-clicked-for-me-part-2-of-2-bafefeac9c33#.gflfyrq5n)

**Comment by rednels** [comment]
认领
