### ISSUE TITLE
Stable functional tests with Genymotion Gradle Plugin and test-specific Product Flavors

### ISSUE THREAD

**Issue by desmond1121** [bboyfeiyu/android-tech-frontier#575]
[link](https://medium.com/@tomaszrykala/stable-functional-tests-with-genymotion-gradle-plugin-and-test-specific-product-flavors-4fe4b93f7c8c#.s43mgu77y)

**Comment by heavenxue** [comment]
@desmond1121  认领该文章

**Comment by heavenxue** [comment]
@heavenxue 认领该文章
