### ISSUE TITLE
An Overview of Android Binder Framework by Rishabh

### ISSUE THREAD

**Issue by seasonwong70** [bboyfeiyu/android-tech-frontier#610]
推荐原因: 这是一篇关于Binder架构的优秀文章
[link](http://codetheory.in/an-overview-of-android-binder-framework/)
@bboyfeiyu 我发现了一篇好文章，求审核

**Comment by hehonghui** [comment]
@seasonwong70 你可以顺带翻译一下  :)

**Comment by seasonwong70** [comment]
@seasonwong 自己认领了

**Comment by seasonwong70** [comment]
@bboyfeiyu 我不知道怎么设置Labels跟Milestone，可以请教一下吗？

**Comment by desmond1121** [comment]
@seasonwong70 没事，直接翻译即可

**Comment by seasonwong70** [comment]
#612
