### ISSUE TITLE
Support 23.2 兼容库

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#614]
Support新版兼容库

[android-support-library-23.2](http://android-developers.blogspot.com/2016/02/android-support-library-232.html)

**Comment by Rogero0o** [comment]
http://2.rogerbolg.sinaapp.com/?p=191#more-191 不知道这篇的质量行不行~行的话我认领了 ：）

**Comment by desmond1121** [comment]
@Rogero0o 效率很快，可以的，提起pr即可，我们校对一遍
