### ISSUE TITLE
关于“我们为什么要用fitsSystemWindows”的一点更正建议

### ISSUE THREAD

**Issue by sachil** [bboyfeiyu/android-tech-frontier#646]
首先感谢项目维护人员的辛勤劳作，这些文章对我帮助很大，谢谢！
进入正题，我在阅读“我们为什么要用fitsSystemWindows”这篇文章的时候，其中有一条注意事项“其它padding将通通被覆盖”，里面解释到“如果你对一个View设置了android:fitsSystemWindows="true"，那么你对该View设置的其他padding将通通无效”。这句话让我产生了疑惑，首先文中提到fitsSystemWindows可以设置给任何view，所以我就理解为给任何view(根view以及子view)设置了android:fitsSystemWindows="true"，那么再给这个view设置padding都将是无效的。但是我通过测试发现，只有根view才是如此，而子view则不是，希望文中能描述得更准确一些。一点个人的想法，最后再次对你们表示感谢

**Comment by zzz40500** [comment]
文中 有讲"fitsSystemWindows 需要被设置给根View " 并且加重,所以我觉得这样的描述已经足够了

**Comment by sachil** [comment]
OK!
