### ISSUE TITLE
A BEGINNERS GUIDE TO AN EFFECTIVE ANDROID TESTING STRATEGY

### ISSUE THREAD

**Issue by chaossss** [bboyfeiyu/android-tech-frontier#658]
[A BEGINNERS GUIDE TO AN EFFECTIVE ANDROID TESTING STRATEGY](https://davidguerrerodiaz.wordpress.com/2016/03/04/a-beginners-guide-to-an-effective-android-testing-strategy/)

**Comment by tanglie1993** [comment]
我可以认领吗？
