### ISSUE TITLE
(About) 10 Things You (Probably) Didn’t Know You Could do in Android Studio

### ISSUE THREAD

**Issue by chaossss** [bboyfeiyu/android-tech-frontier#669]
[(About) 10 Things You (Probably) Didn’t Know You Could do in Android Studio](https://medium.com/google-developers/about-10-things-you-probably-didn-t-know-you-could-do-in-android-studio-de231071b375#.im9teya8w)

**Comment by captainJeck** [comment]
@captainJeck 认领该文章
