### ISSUE TITLE
support-multiple-themes-android-app

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#7]
- 推荐理由 : 在App中应用多主题 
- 原文链接 : http://www.hidroh.com/2015/02/16/support-multiple-themes-android-app/
- 译者 : @bboyfeiyu

**Comment by chaossss** [comment]
chaossss

**Comment by chaossss** [comment]
chaossss

**Comment by chaossss** [comment]
chaossss
