### ISSUE TITLE
Ted Mosby - SOFTWARE ARCHITECT

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/android-tech-frontier#86]
- 推荐理由 :  SOFTWARE ARCHITECT
- 原文链接 : http://hannesdorfmann.com/android/mosby/
- 译者 : Mr.simple

**Comment by hehonghui** [comment]
@chaossss 重要文章哟，你看看~

**Comment by xu6148152** [comment]
今天刚看了，好文。

**Comment by hehonghui** [comment]
@xu6148152 翻译这篇么 ？

**Comment by chaossss** [comment]
@chaossss 认领
