### ISSUE TITLE
Custom Drawables

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/android-tech-frontier#88]
推荐理由:自定义Drawable
原文链接:http://ryanharter.com/blog/2015/04/03/custom-drawables/

**Comment by xu6148152** [comment]
我怎么加Label?

**Comment by hehonghui** [comment]
@xu6148152 可能你没有权限添加Label，这篇比较简单我就没有推荐过来了。

**Comment by hehonghui** [comment]
这是哪位翻译的  ？

**Comment by hehonghui** [comment]
@xu6148152 你最近比较忙哈，给你减轻一下负担，:) 。我把你这篇交给@SwinZ 了，谢啦。

**Comment by hehonghui** [comment]
@SwinZh

**Comment by Wineus** [comment]
@bboyfeiyu 翻译完毕
