### ISSUE TITLE
Dirty Phrasebook

### ISSUE THREAD

**Issue by BillionWang** [bboyfeiyu/android-tech-frontier#89]
推荐理由:脏话手册 (挺好玩的一个应用)，后续文章都是我来做
链接:https://blog.stylingandroid.com/dirty-phrasebook-part-1/
翻译:@BillionWang

**Comment by xu6148152** [comment]
part2:https://blog.stylingandroid.com/dirty-phrasebook-part-2/

**Comment by hehonghui** [comment]
@BillionWang 注意看作者关于他文章的版权声明，加上这个版权声明就OK。https://blog.stylingandroid.com/license-information/ 。用这个网站可以生成模板，http://creativecommons.org/choose/ 。
